export const ENERGY_AVATAR_SERIES = [
  // 1) BABA (1)
  {
    "id": "BAB_01",
    "series": "baba-the-first-energy",
    "seriesName": "BABA: The First Energy",
    "src": "/media/energy-avatar-series/baba-the-first-energy/BAB_01.png",
    "priceUSDC": 1000
  },

  // 2) LEGENDARY (5)
  { "id": "ZSE_01", "series": "legendary-skunk-energy-series", "seriesName": "Legendary Skunk Series", "src": "/media/energy-avatar-series/legendary-skunk-energy-series/ZSE_01.png", "priceUSDC": 500 },
  { "id": "ZSE_02", "series": "legendary-skunk-energy-series", "seriesName": "Legendary Skunk Series", "src": "/media/energy-avatar-series/legendary-skunk-energy-series/ZSE_02.png", "priceUSDC": 500 },
  { "id": "ZSE_03", "series": "legendary-skunk-energy-series", "seriesName": "Legendary Skunk Series", "src": "/media/energy-avatar-series/legendary-skunk-energy-series/ZSE_03.png", "priceUSDC": 500 },
  { "id": "ZSE_04", "series": "legendary-skunk-energy-series", "seriesName": "Legendary Skunk Series", "src": "/media/energy-avatar-series/legendary-skunk-energy-series/ZSE_04.png", "priceUSDC": 500 },
  { "id": "ZSE_05", "series": "legendary-skunk-energy-series", "seriesName": "Legendary Skunk Series", "src": "/media/energy-avatar-series/legendary-skunk-energy-series/ZSE_05.png", "priceUSDC": 500 },

  // 3) YOUNG (20)
  { "id": "SYM_01", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_01.png", "priceUSDC": 250 },
  { "id": "SYM_02", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_02.png", "priceUSDC": 250 },
  { "id": "SYM_03", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_03.png", "priceUSDC": 250 },
  { "id": "SYM_04", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_04.png", "priceUSDC": 250 },
  { "id": "SYM_05", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_05.png", "priceUSDC": 250 },
  { "id": "SYM_06", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_06.png", "priceUSDC": 250 },
  { "id": "SYM_07", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_07.png", "priceUSDC": 250 },
  { "id": "SYM_08", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_08.png", "priceUSDC": 250 },
  { "id": "SYM_09", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_09.png", "priceUSDC": 250 },
  { "id": "SYM_10", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_10.png", "priceUSDC": 250 },
  { "id": "SYM_11", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_11.png", "priceUSDC": 250 },
  { "id": "SYM_12", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_12.png", "priceUSDC": 250 },
  { "id": "SYM_13", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_13.png", "priceUSDC": 250 },
  { "id": "SYM_14", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_14.png", "priceUSDC": 250 },
  { "id": "SYM_15", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_15.png", "priceUSDC": 250 },
  { "id": "SYM_16", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_16.png", "priceUSDC": 250 },
  { "id": "SYM_17", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_17.png", "priceUSDC": 250 },
  { "id": "SYM_18", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_18.png", "priceUSDC": 250 },
  { "id": "SYM_19", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_19.png", "priceUSDC": 250 },
  { "id": "SYM_20", "series": "young-skunk-energy-series", "seriesName": "Young Skunk Series", "src": "/media/energy-avatar-series/young-skunk-energy-series/SYM_20.png", "priceUSDC": 250 },

  // 4) 4TSC_RAR (125)
  { "id": "4TSC_RAR_001", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_001.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_002", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_002.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_003", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_003.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_004", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_004.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_005", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_005.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_006", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_006.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_007", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_007.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_008", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_008.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_009", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_009.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_010", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_010.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_011", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_011.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_012", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_012.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_013", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_013.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_014", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_014.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_015", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_015.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_016", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_016.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_017", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_017.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_018", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_018.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_019", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_019.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_020", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_020.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_021", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_021.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_022", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_022.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_023", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_023.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_024", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_024.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_025", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_025.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_026", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_026.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_027", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_027.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_028", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_028.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_029", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_029.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_030", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_030.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_031", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_031.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_032", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_032.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_033", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_033.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_034", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_034.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_035", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_035.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_036", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_036.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_037", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_037.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_038", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_038.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_039", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_039.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_040", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_040.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_041", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_041.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_042", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_042.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_043", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_043.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_044", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_044.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_045", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_045.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_046", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_046.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_047", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_047.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_048", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_048.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_049", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_049.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_050", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_050.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_051", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_051.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_052", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_052.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_053", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_053.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_054", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_054.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_055", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_055.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_056", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_056.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_057", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_057.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_058", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_058.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_059", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_059.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_060", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_060.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_061", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_061.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_062", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_062.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_063", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_063.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_064", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_064.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_065", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_065.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_066", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_066.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_067", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_067.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_068", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_068.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_069", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_069.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_070", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_070.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_071", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_071.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_072", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_072.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_073", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_073.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_074", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_074.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_075", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_075.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_076", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_076.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_077", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_077.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_078", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_078.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_079", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_079.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_080", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_080.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_081", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_081.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_082", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_082.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_083", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_083.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_084", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_084.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_085", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_085.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_086", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_086.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_087", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_087.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_088", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_088.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_089", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_089.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_090", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_090.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_091", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_091.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_092", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_092.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_093", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_093.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_094", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_094.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_095", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_095.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_096", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_096.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_097", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_097.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_098", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_098.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_099", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_099.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_100", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_100.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_101", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_101.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_102", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_102.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_103", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_103.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_104", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_104.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_105", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_105.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_106", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_106.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_107", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_107.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_108", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_108.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_109", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_109.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_110", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_110.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_111", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_111.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_112", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_112.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_113", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_113.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_114", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_114.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_115", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_115.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_116", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_116.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_117", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_117.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_118", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_118.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_119", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_119.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_120", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_120.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_121", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_121.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_122", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_122.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_123", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_123.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_124", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_124.png", "priceUSDC": 100 },
  { "id": "4TSC_RAR_125", "series": "4TSC_RAR", "seriesName": "4TSC_RAR Series", "src": "/media/energy-avatar-series/4TSC_RAR/4TSC_RAR_125.png", "priceUSDC": 100 },
]


export const ENERGY_AVATAR_SERIES_GROUPS = [
  { key: "baba-the-first-energy", title: "BABA (1)", count: 1, price: 1000 },
  { key: "legendary-skunk-energy-series", title: "LEGENDARY SKUNK SERIES (5)", count: 5, price: 500 },
  { key: "young-skunk-energy-series", title: "YOUNG SKUNK ENERGY SERIES (20)", count: 20, price: 250 },
  { key: "4TSC_RAR", title: "4TSC_RAR (125)", count: 125, price: 100 },
];
